[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
balance_payment = "8Pna6CZRquk83XT6ecisT9TYVfN3hY299GH2yEJk73dL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
cli = "bun run -b scripts/cli.ts"
test = "bun run -b ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
